//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameStore.BLL.BankService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentInfo", Namespace="http://schemas.datacontract.org/2004/07/BankService.Models")]
    [System.SerializableAttribute()]
    public partial class PaymentInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cvv2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ExpirationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal SumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cvv2 {
            get {
                return this.Cvv2Field;
            }
            set {
                if ((object.ReferenceEquals(this.Cvv2Field, value) != true)) {
                    this.Cvv2Field = value;
                    this.RaisePropertyChanged("Cvv2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Sum {
            get {
                return this.SumField;
            }
            set {
                if ((this.SumField.Equals(value) != true)) {
                    this.SumField = value;
                    this.RaisePropertyChanged("Sum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentResult", Namespace="http://schemas.datacontract.org/2004/07/BankService.Models")]
    public enum PaymentResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fail = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotEnoughMoney = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CodeConfirmRequired = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CardDoesntExist = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankService.IBankService")]
    public interface IBankService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/PayByVisa", ReplyAction="http://tempuri.org/IBankService/PayByVisaResponse")]
        GameStore.BLL.BankService.PaymentResult PayByVisa(GameStore.BLL.BankService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/PayByVisa", ReplyAction="http://tempuri.org/IBankService/PayByVisaResponse")]
        System.Threading.Tasks.Task<GameStore.BLL.BankService.PaymentResult> PayByVisaAsync(GameStore.BLL.BankService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/PayByMastercard", ReplyAction="http://tempuri.org/IBankService/PayByMastercardResponse")]
        GameStore.BLL.BankService.PaymentResult PayByMastercard(GameStore.BLL.BankService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/PayByMastercard", ReplyAction="http://tempuri.org/IBankService/PayByMastercardResponse")]
        System.Threading.Tasks.Task<GameStore.BLL.BankService.PaymentResult> PayByMastercardAsync(GameStore.BLL.BankService.PaymentInfo info);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/Confirm", ReplyAction="http://tempuri.org/IBankService/ConfirmResponse")]
        bool Confirm(string code);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankService/Confirm", ReplyAction="http://tempuri.org/IBankService/ConfirmResponse")]
        System.Threading.Tasks.Task<bool> ConfirmAsync(string code);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankServiceChannel : GameStore.BLL.BankService.IBankService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankServiceClient : System.ServiceModel.ClientBase<GameStore.BLL.BankService.IBankService>, GameStore.BLL.BankService.IBankService {
        
        public BankServiceClient() {
        }
        
        public BankServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GameStore.BLL.BankService.PaymentResult PayByVisa(GameStore.BLL.BankService.PaymentInfo info) {
            return base.Channel.PayByVisa(info);
        }
        
        public System.Threading.Tasks.Task<GameStore.BLL.BankService.PaymentResult> PayByVisaAsync(GameStore.BLL.BankService.PaymentInfo info) {
            return base.Channel.PayByVisaAsync(info);
        }
        
        public GameStore.BLL.BankService.PaymentResult PayByMastercard(GameStore.BLL.BankService.PaymentInfo info) {
            return base.Channel.PayByMastercard(info);
        }
        
        public System.Threading.Tasks.Task<GameStore.BLL.BankService.PaymentResult> PayByMastercardAsync(GameStore.BLL.BankService.PaymentInfo info) {
            return base.Channel.PayByMastercardAsync(info);
        }
        
        public bool Confirm(string code) {
            return base.Channel.Confirm(code);
        }
        
        public System.Threading.Tasks.Task<bool> ConfirmAsync(string code) {
            return base.Channel.ConfirmAsync(code);
        }
    }
}
