// <auto-generated />
namespace GameStore.DAL.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Gamedates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Gamedates));
        
        string IMigrationMetadata.Id
        {
            get { return "201510270923242_Game dates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
